---
- hosts: all
  gather_facts: yes
  vars_files:
    - "./host_vars/odin.yml"
  pre_tasks:
    # TODO: Turn into roles
    # - import_tasks: tasks/cli-packages.yml
    # - import_tasks: tasks/gui-packages.yml
  roles:
    # - {role: 'marcus-grant.mydotfiles', tags: 'dotfiles'}
    # - {role: 'keyboard', tags: 'keyboard'}
    # - {role: 'asdf', tags: ['dev', 'asdf']}
    # - gnome
    # - fonts
    - {role: 'undervolt', tags: ['undervolt', 'power', 'hardware']}
