---
- hosts: all
  gather_facts: yes
  tasks:
  roles:
    - marcus-grant.bootstrap-ansible-arch
    - marcus-grant.mydotfiles
    - { name: roles/my-common-packages, become: yes }
  post_tasks:
    - import_tasks: tasks/extra-cli-packages.yml
    - import_tasks: tasks/extra-gui-packages.yml
