---
- hosts: all
  gather_facts: yes
  pre_tasks:
    - name: ensure python is installed
      raw: test -e /usr/bin/python || (pacman --noconfirm -S python)
      become: yes
      changed_when: no
    - import_tasks: tasks/cli-packages.yml
    - import_tasks: tasks/gui-packages.yml
  roles:
    - marcus-grant.bootstrap-ansible-arch
    - { name: roles/my-common-packages, become: yes }
    - marcus-grant.mydotfiles
    - marcus-grant.common-packages
    - fonts
    - gnome
