---
- hosts: all
  gather_facts: yes
  tasks:
  roles:
  post_tasks:
    - import_tasks: tasks/extra-cli-packages.yml
    - import_tasks: tasks/extra-gui-packages.yml
      when: >-
        extra_gui_packages is defined and extra_gui_packages | length > 0
