---
- hosts: power
  gather_facts: true
  become: true
  pre_tasks:
  # tasks:
    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
    - name: 'Ensure bulk packages installed first, from "installed_packages var"'
      apt:
        name: '{{ item }}'
        state: present
      loop: '{{ installed_packages }}'
    - name: "Manage flathub repos"
      community.general.flatpak_remote:
        name: "flathub"
        state: "present"
        flatpakrepo_url: "https://dl.flathub.org/repo/flathub.flatpakrepo"
        method: "system"
  roles:
    - marcus-grant.mydotfiles

    # - keyboard
    # - asdf
    # - gnome
    # - fonts
    # - undervolt


- hosts: power
  gather_facts: true
  roles:
    - marcus-grant.mydotfiles
    - zsh
  post_tasks:
    - name: "Manage flathub repos (user)"
      community.general.flatpak_remote:
        name: "flathub"
        state: "present"
        flatpakrepo_url: "https://dl.flathub.org/repo/flathub.flatpakrepo"
        method: "user"
    - name: Install flatpaks
      community.general.flatpak:
        name: '{{ item }}'
        state: present
        method: user
      loop: '{{ flatpaks }}'
    - name: Check if Steam flatpak has already added steam_library_path (host_var only)
      shell: 'flatpak info --show-permissions com.valvesoftware.Steam | grep "{{steam_library_path}}"'
      register: flatpak_steam
      failed_when: false
      changed_when: false
    - debug:
        msg: '{{flatpak_steam}}'
    - name: Permit Steam flatpak to use steam games directory
      shell: 'flatpak override --user --filesystem={{ steam_library_path }} com.valvesoftware.Steam'
      when: "'com.valvesoftware.Steam' in flatpaks and flatpak_steam.rc != 0"
