---
# A task that allows specifying at host or group level extra packages...
# ... to install that have dont have a gui.
- name: install cli_packages
  become: yes
  package:
    name: '{{ item }}'
    state: present
  loop: '{{ cli_packages }}'
  when: >-
    cli_packages is defined and cli_packages | length > 0