---
# A task that allows specifying at host or group level extra packages...
# ... to install that have a gui.
- name: install gui_packages
  become: yes
  package:
    name: '{{ item }}'
    state: present
  loop: '{{ gui_packages }}'
  when: >-
    (gui_packages is defined) and (gui_packages | length > 0)