---
### keyboard dconf mapping options
keyboard_dconf_xkb_remaps_enable: true
keyboard_dconf_options: "['caps:escape', 'lv3:ralt_switch']"
  # - "caps:escape"  # caps becomes escape
  # - "lv3:ralt_switch"  # RALT layer 3 int'l char maps

### packages for cli-packages install task
installed_packages:
  # - alacritty  # complications in debian apt sources - works on sid
  - baobab
  - borgmatic
  - borgbackup
  - bpytop
  - cowsay
  - curl
  - dconf-cli
  - dconf-editor
  - fd-find
  - ffmpeg
  - flatpak
  - fzf
  - git
  - guake
  - gnome-tweaks
  - gparted
  - htop
  - iotop
  - libvirt-daemon  # TODO Move these to a virtualization role
  - libvirt-daemon-driver-lxc
  - libvirt-daemon-driver-qemu
  - libvirt-daemon-driver-vbox
  - lm-sensors
  - lutris
  - lolcat
  - ncdu
  - neovim
  - nodejs
  - npm
  - openssh-server
  - openssl
  - pandoc
  - python3-psutil
  - ranger
  - ripgrep
  - snapper
  - tig
  - timeshift
  - tmux
  - tree
  - unzip
  - vim
  - weechat
  - wget
  - xclip
  - yarnpkg
  - zsh
  

### flatpak installations task
flatpaks:
  - com.belmoussaoui.Authenticator
  - com.borgbase.Vorta
  - com.discordapp.Discord
  - com.github.alainm23.planner
  - com.github.Eloston.UngoogledChromium
  - com.github.muriloventuroso.easyssh
  - com.github.qarmin.czkawka
  - com.github.tchx84.Flatseal
  - com.microsoft.Teams
  - com.rafaelmardojai.Blanket
  - com.spotify.Client
  - com.todoist.Todoist
  - com.valvesoftware.Steam
  - com.valvesoftware.Steam.CompatibilityTool.Proton-GE
  - com.visualstudio.code
  - io.github.antimicrox.antimicrox
  - im.pidgin.Pidgin
  - im.riot.Riot
  - org.freecadweb.FreeCAD 
  - org.gimp.GIMP
  - org.gnome.Boxes
  - org.gnome.Epiphany
  - org.gnome.Evolution
  - org.gtk.Gtk3theme.Pop-dark
  - org.inkscape.Inkscape
  - org.libreoffice.LibreOffice
  - org.mozilla.firefox
  - org.mozilla.Thunderbird
  - org.openscad.OpenSCAD

### dotfiles
dotfiles_local_root_dir: '~/.dots'
dotfiles_git_server_base_url: 'github.com'
dotfiles_git_username: 'marcus-grant'
dotfiles_use_ssh: true
dotfiles:
  bash:
    repo_name: 'dots-bash'
    local_subdir_name: 'bash'
    version: 'main'
    links:
      - { dest: '~/.bashrc', src: '~/.dots/bash/rc.bash' }
      - { dest: '~/.bash_profile', src: '~/.dots/bash/profile.bash' }
  vim:
    repo_name: 'dots-vim'
    local_subdir_name: 'vim'
    version: 'main'
    links:
      - { dest: '~/.vim', src: '~/.dots/vim' }
      - { dest: '~/.vimrc', src: '~/.dots/vim/vimrc' }
  neovim:
    repo_name: 'dots-neovim'
    local_subdir_name: 'neovim'
    version: 'master'
    links:
      - { dest: '~/.config/nvim', src: '~/.dots/neovim' }
  tmux:
    repo_name: 'dots-tmux'
    local_subdir_name: 'tmux'
    version: 'main'
    links:
      - { dest: '~/.tmux.conf', src: '~/.dots/tmux/.tmux.conf' }
      - { dest: '~/.tmux.conf.local', src: '~/.dots/tmux/.tmux.conf.local' }
  alacritty:
    repo_name: 'dots-alacritty'
    local_subdir_name: 'alacritty'
    version: 'master'
    links:
      - { dest: '~/.config/alacritty', src: '~/.dots/alacritty' }
  i3:
    repo_name: 'dots-i3'
    local_subdir_name: 'i3'
    version: 'master'
    links:
      - { dest: '~/.config/i3', src: '~/.dots/i3' }
