---
# TODO: split these out by os_family
# defaults file for fonts
fonts_from_packages:
  - otf-fira-sans
  - ttf-roboto
  - ttf-ubuntu-font-family
  - ttf-ubuntu-font-family
  - noto-fonts-emoji
  - noto-fonts
  # - nerd-fonts-noto-sans-mono

fonts_from_aur:
  - ttf-roboto-slab

# These aren't os-specific (for unix-based)
fonts_from_http:
  - local_subdir: iosevka
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.0.0/Iosevka.zip
  - local_subdir: firacode
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.0.0/FiraCode.zip
  - local_subdir: terminus
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.0.0/Terminus.zip
  - local_subdir: source-code-pro
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.0.0/SourceCodePro.zip
  - local_subdir: inconsolata-go
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.0.0/InconsolataGo.zip

