---
### packages for cli-packages install task
cli_packages:
  - neovim
  - dconf
  - ffmpeg
  - lm_sensors
  - pandoc
  - cowsay
  - cowfortune
  - lolcat
  - xclip
  - python-psutil
  - python-neovim # consider putting these in a python dev env role?
  - nodejs # consider putting into a nvm/node/npm role also have it install node neovim helper
  - npm # same as above
  - yarn # same as above


### packages for gui-packages install task
gui_packages:
  - firefox
  - chromium
  - alacritty
  - guake
  # - timeshift needs aur
  - baobab
  - dconf-editor
