---
# These need to be specific to the package names of the os-family
- import_tasks: fonts-Archlinux.yml
  when: ansible_facts['os_family'] == "Archlinux"

- name: make sure user font folder is available
  file:
    path: '~/.local/share/fonts'
    state: directory
    mode: 0755

- debug:
    msg: '{{ item.url | splitext }}'
  loop: fonts_set

# - include_tasks: ./fonts-single-download.yml
#   when:
#   loop: '{{ fonts_sets }}'

# - name: ensure unzip is installed for unarchive fetching zip fonts
#   become: yes
#   pacman:
#     name: unzip
#     state: present

# - include_tasks: ./fonts-archive-download.yml
#   loop: '{{ fonts_sets }}'

# TODO: Consider having a section dedicated to ansible controller local fonts
# - name: rsync playbook stored font files to font folder
#   synchronize:
#     src: '{{ role_path }}/files/*'
#     dest: '~/.local/share/fonts' # required. Path on the destination host that will be synchronized from the source; The path can be absolute or relative.
#     rsync_timeout: 30
#     # owner: "{{ lookup('env','USER') }}"
#     # existing_only: no # not required. Skip creating new files on receiver.
#     archive: yes
#     mode: pull
